WDL-OL/IPlug: IPlugBase Class Reference
IPlugBase Class Reference abstract
The lowest level base class of an IPlug plug-in.
#include <IPlugBase.h>
Public Member Functions
IPlugBase (IPlugConfig config, EAPI plugAPI)
virtual void OnParamChange (int paramIdx, EParamSource source)
Override this method to do something when a parameter changes.
virtual void OnParamChange (int paramIdx)
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
virtual bool SerializeState (IByteChunk &chunk)
Override this method to serialize custom state data, if your plugin does state chunks.
virtual int UnserializeState (const IByteChunk &chunk, int startPos)
Override this method to unserialize custom state data, if your plugin does state chunks.
virtual bool CompareState (const uint8_t *pIncomingState, int startPos)
Override this method to implement a custom comparison of incoming state data with your plug-ins state data, in order to support the ProTools compare light when using custom state chunks.
virtual void OnUIOpen ()
Override this method to be notified when the UI is opened.
virtual void OnUIClose ()
Override this method to be notified when the UI is closed.
virtual void * OpenWindow (void *pHandle)
Override this method when not using IGraphics in order to return a platform view handle e.g.
virtual void CloseWindow ()
Override this method when not using IGraphics if you need to free resources etc when the window closes.
virtual void OnWindowResize ()
Implement this to do something after the user interface is resized.
virtual bool OnHostRequestingAboutBox ()
virtual void OnHostIdentified ()
Implement this to do something specific when IPlug becomes aware of the particular host that is hosting the plug-in.
virtual bool GetMidiNoteText (int noteNumber, char *str) const
Override this method to provide custom text linked to MIDI note numbers in API classes that support that (VST2) Typically this might be used for a drum machine plug-in, in order to label a certainty "kick drum" etc.
virtual void * GetAAXViewInterface ()
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
virtual void OnRestoreState ()
This is called by API classes after restoring stateand by IPlugPresetHandler::RestorePreset().
virtual void PrintDebugInfo () const
Helper method, used to print some info to the console in debug builds.
int NParams () const
IParam * GetParam (int paramIdx)
Get a pointer to one of the plug-ins IParam objects WARNING: The IPlugBase::mParams is accessed by multiple threads, and this method has no thread safety mechanism.
const char * GetPluginName () const
int GetPluginVersion (bool decimal) const
Get the plug-in version number.
void GetPluginVersionStr (WDL_String &str) const
Gets the plug-in version as a string.
const char * GetMfrName () const
Get the manufacturer name as a CString.
const char * GetProductName () const
Get the product name as a CString.
int GetUniqueID () const
int GetMfrID () const
virtual EHost GetHost ()
int GetHostVersion (bool decimal)
Get the host version number as an integer.
void GetHostVersionStr (WDL_String &str)
Get the host version number as a string.
EAPI GetAPI () const
const char * GetAPIStr () const
const char * GetArchStr () const
void GetBuildInfoStr (WDL_String &str) const
Used to get the build date of the plug-in and architecture/api details in one string.
bool DoesStateChunks () const
bool HasUI () const
int Width () const
int Height () const
void DirtyParameters ()
This method will loop through all parameters, telling the host that they changed.
virtual void ResizeGraphics ()=0
Call this method in order to notify the API of a graphics resize.
virtual void BeginInformHostOfParamChange (int paramIdx)=0
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
virtual void EndInformHostOfParamChange (int paramIdx)=0
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
void SetParameterValue (int paramIdx, double normalizedValue)
SetParameterValue is called from the UI in the middle of a parameter change gesture (possibly via delegate) in order to update a parameter's value.
virtual void InformHostOfProgramChange ()
Implemented by the API class, called by the UI (etc) when the plug-in initiates a program/preset change (not applicable to all APIs)
virtual void SendParameterValueToUIFromAPI (int paramIdx, double value, bool normalized)
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange()
int NParamGroups ()
int AddParamGroup (const char *name)
Called to add a parameter group name, when a unique group name is discovered.
const char * GetParamGroupName (int idx)
Get the parameter group name as a particular index.
void InitChunkWithIPlugVer (IByteChunk &chunk)
int GetIPlugVerFromChunk (const IByteChunk &chunk, int &pos)
Helper method to retrieve the IPlug version number from the beginning of the byte chunk.
void SetHost (const char *host, int version)
Called to set the name of the current host, if known.
virtual void HostSpecificInit ()
This method is called by some API classes, in order to do specific initialisation for particular problematic hosts.
bool SerializeParams (IByteChunk &chunk)
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
int UnserializeParams (const IByteChunk &chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
void OnParamReset (EParamSource source)
Calls OnParamChange() for each parameter and finally OnReset().
Public Attributes
WDL_Mutex mParams_mutex
Lock when accessing mParams (including via GetParam) from the audio thread.
WDL_String mParamDisplayStr
Protected Attributes
WDL_String mPluginName
The name of this plug-in.
WDL_String mProductName
Product name: if the plug-in is part of collection of plug-ins it might be one product.
WDL_String mMfrName
Plug-in Manufacturer name.
int mUniqueID
int mMfrID
int mVersion
Plug-in version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
int mHostVersion = 0
Host version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
EHost mHost = kHostUninit
Host that has been identified, see EHost enum.
EAPI mAPI
API of this instance.
bool mStateChunks = false
true if the plug-in does opaque state chunks.
bool mHasUI = false
true if the plug-in has a user interface.
int mWidth = 0
The default width of the plug-in UI if it has an interface.
int mHeight = 0
The default height of the plug-in UI if it has an interface.
WDL_PtrList< const char > mParamGroups
A list of unique cstrings found specified as "parameter groups" when defining IParams.
WDL_PtrList< IParam > mParams
A list of IParam objects.
Detailed Description
The lowest level base class of an IPlug plug-in.
No UI framework code included. This interface does not handle audio processing, see
Definition at line 24 of file IPlugBase.h.
Member Function Documentation
int IPlugBase::AddParamGroup (const char * name) inline
Called to add a parameter group name, when a unique group name is discovered.
Parameters
name CString for the unique group name
Returns
Number of parameter groups
Definition at line 213 of file IPlugBase.h.
References mParamGroups, and NParamGroups().
virtual void IPlugBase::BeginInformHostOfParamChange (int paramIdx) pure virtual
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Implemented in IPlugAAX, IPlugAU, IPlugAPP, IPlugVST3, IPlugVST, IPlugAUv3, and IPlugWAM.
Referenced by IPlugBaseGraphics::BeginInformHostOfParamChangeFromUI().
bool IPlugBase::CompareState (const uint8_t * pIncomingState, int startPos) virtual
Override this method to implement a custom comparison of incoming state data with your plug-ins state data, in order to support the ProTools compare light when using custom state chunks.
The default implementation will compare the serialized parameters.
Parameters
incomingState The incoming state data
startPos The position to start in the incoming data in bytes
Returns
true in order to indicate that the states are equal.
Definition at line 44 of file IPlugBase.cpp.
References GetParam(), NParams(), and IParam::Value().
void IPlugBase::DirtyParameters ()
This method will loop through all parameters, telling the host that they changed.
You can use it if you restore a preset using a custom preset mechanism.
Definition at line 197 of file IPlugBase.cpp.
References GetParam(), and NParams().
bool IPlugBase::DoesStateChunks () const inline
Returns
true if the plug-in has been set up to do state chunks, via config.h
Definition at line 165 of file IPlugBase.h.
References mStateChunks.
virtual void IPlugBase::EndInformHostOfParamChange (int paramIdx) pure virtual
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Implemented in IPlugAAX, IPlugAU, IPlugAPP, IPlugVST3, IPlugVST, IPlugAUv3, and IPlugWAM.
Referenced by IPlugBaseGraphics::EndInformHostOfParamChangeFromUI().
virtual void* IPlugBase::GetAAXViewInterface () inline virtual
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
Returns
pointer to the class that implements the IAAXViewInterface
Reimplemented in IPlugBaseGraphics.
Definition at line 93 of file IPlugBase.h.
EAPI IPlugBase::GetAPI () const inline
Returns
The The plug-in API, see EAPI enum for a list of possible APIs
Definition at line 151 of file IPlugBase.h.
References mAPI.
Referenced by GetAPIStr().
const char * IPlugBase::GetAPIStr () const
Returns
Returns a CString describing the plug-in API, e.g. "VST2"
Definition at line 107 of file IPlugBase.cpp.
References GetAPI().
Referenced by GetBuildInfoStr().
const char * IPlugBase::GetArchStr () const
Returns
Returns a CString either "x86" or "x64" describing the binary architecture
Definition at line 120 of file IPlugBase.cpp.
Referenced by GetBuildInfoStr().
void IPlugBase::GetBuildInfoStr (WDL_String & str) const
Used to get the build date of the plug-in and architecture/api details in one string.
Note
since the implementation is in IPlugBase.cpp, you may want to touch that file as part of your build script to force recompilation
Parameters
str WDL_String will be set with the Plugin name, architecture, api, build date, build time
Definition at line 129 of file IPlugBase.cpp.
References GetAPIStr(), GetArchStr(), GetPluginName(), and GetPluginVersionStr().
Referenced by IPlugBaseGraphics::PrintDebugInfo(), and PrintDebugInfo().
virtual EHost IPlugBase::GetHost () inline virtual
Returns
The host if it has been identified, see EHost enum for a list of possible hosts, implemented in the API class for VST2 and AUv2
Reimplemented in IPlugAU, IPlugVST, and IPlugWAM.
Definition at line 139 of file IPlugBase.h.
References mHost.
Referenced by IPlugVST::GetHost(), IPlugAU::GetHost(), GetHostVersion(), and GetHostVersionStr().
int IPlugBase::GetHostVersion (bool decimal)
Get the host version number as an integer.
Parameters
decimal true indicates decimal format = VVVVRRMM, otherwise hexadecimal 0xVVVVRRMM.
Returns
The host version number as an integer.
Definition at line 91 of file IPlugBase.cpp.
References GetHost(), and mHostVersion.
void IPlugBase::GetHostVersionStr (WDL_String & str)
Get the host version number as a string.
Parameters
str string into which to write the host version
Definition at line 101 of file IPlugBase.cpp.
References GetHost(), and mHostVersion.
int IPlugBase::GetIPlugVerFromChunk (const IByteChunk & chunk, int & pos)
Helper method to retrieve the IPlug version number from the beginning of the byte chunk.
Parameters
chunk The incoming byte chunk that contains the version number
pos The position (in bytes) to start looking
Returns
The IPlug version number, retrieved from the chunk, or 0 if it failed
Definition at line 215 of file IPlugBase.cpp.
int IPlugBase::GetMfrID () const inline
Returns
The plug-in manufacturer's unique four character ID as an integer
Definition at line 136 of file IPlugBase.h.
virtual bool IPlugBase::GetMidiNoteText (int noteNumber, char * str) const inline virtual
Override this method to provide custom text linked to MIDI note numbers in API classes that support that (VST2) Typically this might be used for a drum machine plug-in, in order to label a certainty "kick drum" etc.
Parameters
noteNumber MIDI note to get the textual description for
str char array to set the text for the note. Should be less thatn kVstMaxNameLen (64) characters
Returns
return true if you specified a custom textual description for this note
Definition at line 88 of file IPlugBase.h.
IParam* IPlugBase::GetParam (int paramIdx) inline
Get a pointer to one of the plug-ins IParam objects WARNING: The IPlugBase::mParams is accessed by multiple threads, and this method has no thread safety mechanism.
Parameters
paramIdx The index of the parameter object to be got
Returns
A pointer to the IParam object at paramIdx
Definition at line 109 of file IPlugBase.h.
References mParams.
Referenced by CompareState(), DirtyParameters(), IPlugBaseGraphics::GetParamObjectFromUI(), IPlugBaseGraphics::SendParameterValueToUIFromDelegate(), and SetParameterValue().
const char* IPlugBase::GetParamGroupName (int idx) inline
Get the parameter group name as a particular index.
Parameters
idx The index to return
Returns
CString for the unique group name
Definition at line 218 of file IPlugBase.h.
References mParamGroups.
const char* IPlugBase::GetPluginName () const inline
Returns
the name of the plug-in as a CString
Definition at line 112 of file IPlugBase.h.
References mPluginName.
Referenced by GetBuildInfoStr().
int IPlugBase::GetPluginVersion (bool decimal) const
Get the plug-in version number.
Parameters
decimal Sets the output format
Returns
Effect version in VVVVRRMM (if decimal is true) or Hexadecimal 0xVVVVRRMM (if decimal is false) format
Definition at line 72 of file IPlugBase.cpp.
References mVersion.
void IPlugBase::GetPluginVersionStr (WDL_String & str) const
Gets the plug-in version as a string.
Parameters
str WDL_String to write to The output format is vX.M.m, where X - version, M - major, m - minor
Note
If _DEBUG is defined, D is appended to the version string
If TRACER_BUILD is defined, T is appended to the version string
Definition at line 80 of file IPlugBase.cpp.
References mVersion.
Referenced by GetBuildInfoStr().
const char* IPlugBase::GetProductName () const inline
Get the product name as a CString.
A shipping product may contain multiple plug-ins, hence this. Not used in all APIs
Definition at line 130 of file IPlugBase.h.
References mProductName.
int IPlugBase::GetUniqueID () const inline
Returns
The plug-in's unique four character ID as an integer
Definition at line 133 of file IPlugBase.h.
bool IPlugBase::HasUI () const inline
Returns
true if the plug-in is meant to have a UI, as defined in config.h
Definition at line 168 of file IPlugBase.h.
References mHasUI.
Referenced by IPlugVST::ResizeGraphics(), IPlugAPP::ResizeGraphics(), IPlugVST3::ResizeGraphics(), IPlugAU::ResizeGraphics(), and IPlugAAX::ResizeGraphics().
int IPlugBase::Height () const inline
Returns
The default height of the plug-in UI in pixels, if defined in config.h
Definition at line 174 of file IPlugBase.h.
References mHeight.
Referenced by IPlugVST::ResizeGraphics(), IPlugAPP::ResizeGraphics(), IPlugVST3::ResizeGraphics(), and IPlugAAX::ResizeGraphics().
virtual void IPlugBase::HostSpecificInit () inline virtual
This method is called by some API classes, in order to do specific initialisation for particular problematic hosts.
This is not the same as OnHostIdentified(), which you may implement in your plug-in class to do your own specific initialisation after a host has been identified
Reimplemented in IPlugAU, IPlugVST, and IPlugWAM.
Definition at line 235 of file IPlugBase.h.
int IPlugBase::NParamGroups () inline
Returns
The number of unique parameter groups identified
Definition at line 208 of file IPlugBase.h.
References mParamGroups.
Referenced by AddParamGroup().
int IPlugBase::NParams () const inline
Returns
Returns the number of parameters that belong to the plug-in.
Definition at line 103 of file IPlugBase.h.
References mParams.
Referenced by CompareState(), and DirtyParameters().
virtual void IPlugBase::OnHostIdentified () inline virtual
Implement this to do something specific when IPlug becomes aware of the particular host that is hosting the plug-in.
The method may get called multiple times.
Definition at line 81 of file IPlugBase.h.
Referenced by IPlugVST::HostSpecificInit(), and IPlugAU::HostSpecificInit().
void IPlugBase::OnParamChange (int paramIdx, EParamSource source) virtual
Override this method to do something when a parameter changes.
THIS METHOD CAN BE CALLED BY THE HIGH PRIORITY AUDIO THREAD
Parameters
paramIdx The index of the parameter that changed
source One of the EParamSource options to indicate where the parameter change came from.
Definition at line 38 of file IPlugBase.cpp.
Referenced by OnParamReset(), and SetParameterValue().
virtual void IPlugBase::OnParamChange (int paramIdx) inline virtual
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
Definition at line 40 of file IPlugBase.h.
void IPlugBase::OnParamReset (EParamSource source)
Calls OnParamChange() for each parameter and finally OnReset().
Parameters
source Specifies the source of this parameter change
Definition at line 156 of file IPlugBase.cpp.
References mParams, and OnParamChange().
Referenced by UnserializeParams().
virtual void IPlugBase::OnRestoreState () inline virtual
This is called by API classes after restoring stateand by IPlugPresetHandler::RestorePreset().
Typically used to update user interface, where parameter values have changed.
Reimplemented in IPlugBaseGraphics.
Definition at line 96 of file IPlugBase.h.
virtual void IPlugBase::OnUIClose () inline virtual
Override this method to be notified when the UI is closed.
Definition at line 65 of file IPlugBase.h.
virtual void IPlugBase::OnUIOpen () inline virtual
Override this method to be notified when the UI is opened.
Definition at line 62 of file IPlugBase.h.
virtual void* IPlugBase::OpenWindow (void * pHandle) inline virtual
Override this method when not using IGraphics in order to return a platform view handle e.g.
NSView, UIView, HWND
Reimplemented in IPlugBaseGraphics.
Definition at line 68 of file IPlugBase.h.
void IPlugBase::PrintDebugInfo () const virtual
Helper method, used to print some info to the console in debug builds.
Can be overridden in other IPlugBases, for specific functionality, such as printing UI details.
Reimplemented in IPlugBaseGraphics.
Definition at line 65 of file IPlugBase.cpp.
References GetBuildInfoStr().
Referenced by IPlugBaseGraphics::PrintDebugInfo().
virtual void IPlugBase::ResizeGraphics () pure virtual
Call this method in order to notify the API of a graphics resize.
Implemented in IPlugAAX, IPlugAU, IPlugVST3, IPlugAPP, IPlugVST, and IPlugAUv3.
virtual void IPlugBase::SendParameterValueToUIFromAPI (int paramIdx, double value, bool normalized) inline virtual
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange()
Parameters
paramIdx The index of the parameter that changed
value The new value
normalized /true if
value is normalised
Reimplemented in IPlugBaseGraphics.
Definition at line 205 of file IPlugBase.h.
bool IPlugBase::SerializeParams (IByteChunk & chunk)
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
Parameters
chunk The output chunk to serialize to. Will append data if the chunk has already been started.
Returns
return true if the serialization was successful
Definition at line 164 of file IPlugBase.cpp.
References mParams, and IParam::Value().
Referenced by SerializeState().
virtual bool IPlugBase::SerializeState (IByteChunk & chunk) inline virtual
Override this method to serialize custom state data, if your plugin does state chunks.
Parameters
chunk The output bytechunk where data can be serialized
Returns
true if serialization was successful
Definition at line 45 of file IPlugBase.h.
References SerializeParams().
void IPlugBase::SetHost (const char * host, int version)
Called to set the name of the current host, if known.
Parameters
host The name of the plug-in host
version The version of the plug-in host where version in hex = 0xVVVVRRMM
Definition at line 138 of file IPlugBase.cpp.
References LookUpHost(), mHost, and mHostVersion.
Referenced by IPlugVST::GetHost(), and IPlugAU::GetHost().
void IPlugBase::SetParameterValue (int paramIdx, double normalizedValue)
SetParameterValue is called from the UI in the middle of a parameter change gesture (possibly via delegate) in order to update a parameter's value.
It will update mParams[paramIdx], call InformHostOfParamChange and IPlugBase::OnParamChange();
Parameters
idx The index of the parameter that changed
normalizedValue The new (normalised) value
Definition at line 148 of file IPlugBase.cpp.
References GetParam(), and OnParamChange().
Referenced by IPlugBaseGraphics::SetParameterValueFromUI().
int IPlugBase::UnserializeParams (const IByteChunk & chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
Parameters
chunk The incoming chunk where parameter values are stored to unserialize
startPos The start position in the chunk where parameter values are stored
Returns
The new chunk position (endPos)
Definition at line 179 of file IPlugBase.cpp.
References mParams, OnParamReset(), IParam::Set(), and IParam::Value().
Referenced by UnserializeState().
virtual int IPlugBase::UnserializeState (const IByteChunk & chunk, int startPos) inline virtual
Override this method to unserialize custom state data, if your plugin does state chunks.
Implementations should call UnserializeParams() after custom data is unserialized
Parameters
chunk The incoming chunk containing the state data.
startPos The position in the chunk where the data starts
Returns
The new chunk position (endPos)
Definition at line 52 of file IPlugBase.h.
References UnserializeParams().
int IPlugBase::Width () const inline
Returns
The default width of the plug-in UI in pixels, if defined in config.h
Definition at line 171 of file IPlugBase.h.
References mWidth.
Referenced by IPlugVST::ResizeGraphics(), IPlugAPP::ResizeGraphics(), IPlugVST3::ResizeGraphics(), and IPlugAAX::ResizeGraphics().
Member Data Documentation
bool IPlugBase::mHasUI = false protected
true if the plug-in has a user interface.
If false the host will provide a default interface
Definition at line 279 of file IPlugBase.h.
Referenced by HasUI().
int IPlugBase::mHeight = 0 protected
The default height of the plug-in UI if it has an interface.
Definition at line 283 of file IPlugBase.h.
Referenced by Height().
WDL_PtrList<const char> IPlugBase::mParamGroups protected
A list of unique cstrings found specified as "parameter groups" when defining IParams.
These are used in various APIs to group parameters together in automation dialogues.
Definition at line 285 of file IPlugBase.h.
Referenced by AddParamGroup(), GetParamGroupName(), and NParamGroups().
WDL_PtrList<IParam> IPlugBase::mParams protected
A list of IParam objects.
This list is resized in the IPlugBase constructor depending on the number of parameters passed as an argument to IPLUG_CTOR in the plugin class implementation constructor
Definition at line 287 of file IPlugBase.h.
Referenced by GetParam(), NParams(), OnParamReset(), IPlugBaseGraphics::OnRestoreState(), SerializeParams(), and UnserializeParams().
bool IPlugBase::mStateChunks = false protected
true if the plug-in does opaque state chunks.
If false the host will provide a default interface
Definition at line 277 of file IPlugBase.h.
Referenced by DoesStateChunks().
int IPlugBase::mWidth = 0 protected
The default width of the plug-in UI if it has an interface.
Definition at line 281 of file IPlugBase.h.
Referenced by Width().
The documentation for this class was generated from the following files:
IPlugBase.h
IPlugBase.cpp