WDL-OL/IPlug: IPlugBaseGraphics Class Reference
IPlugBaseGraphics Class Reference
An IPlugBase class for an IPlug plug-in that uses IGraphics for it's UI.
#include <IPlugBaseGraphics.h>
Public Member Functions
IPlugBaseGraphics (IPlugConfig config, EAPI plugAPI)
void * GetAAXViewInterface () override
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
void * OpenWindow (void *pHandle) override
Override this method when not using IGraphics in order to return a platform view handle e.g.
void CloseWindow () override
Override this method when not using IGraphics if you need to free resources etc when the window closes.
void SendParameterValueToUIFromAPI (int paramIdx, double value, bool normalized) override
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange()
void PrintDebugInfo () const override
Helper method, used to print some info to the console in debug builds.
virtual void OnRestoreState () override
If you override this method you should call this parent, or implement the same functionality in order to get controls to update, when state is restored.
void SetControlValueFromDelegate (int controlIdx, double normalizedValue) override
In IGraphics plug-ins, this method is used to update IControls in the user interface from the plug-in class, when the control is not linked to a parameter, for example a typical use case would be a meter control.
void SendParameterValueToUIFromDelegate (int paramIdx, double value, bool normalized) override
This method is called by the API class in order to update the user interface with the new parameter values, typically after automation.
const IParam * GetParamObjectFromUI (int paramIdx) override
Called by the user interface in order to get a const pointer to an IParam object.
void SetParameterValueFromUI (int paramIdx, double value) override
Called by the user interface during a parameter change gesture, in order to notify the host of the new value (via a call in the API class)
void BeginInformHostOfParamChangeFromUI (int paramIdx) override
Called by the user interface at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void EndInformHostOfParamChangeFromUI (int paramIdx) override
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void AttachGraphics (IGraphics *pGraphics)
IGraphics * GetUI ()
Public Member Functions inherited from IPlugBase
IPlugBase (IPlugConfig config, EAPI plugAPI)
virtual void OnParamChange (int paramIdx, EParamSource source)
Override this method to do something when a parameter changes.
virtual void OnParamChange (int paramIdx)
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
virtual bool SerializeState (IByteChunk &chunk)
Override this method to serialize custom state data, if your plugin does state chunks.
virtual int UnserializeState (const IByteChunk &chunk, int startPos)
Override this method to unserialize custom state data, if your plugin does state chunks.
virtual bool CompareState (const uint8_t *pIncomingState, int startPos)
Override this method to implement a custom comparison of incoming state data with your plug-ins state data, in order to support the ProTools compare light when using custom state chunks.
virtual void OnUIOpen ()
Override this method to be notified when the UI is opened.
virtual void OnUIClose ()
Override this method to be notified when the UI is closed.
virtual void OnWindowResize ()
Implement this to do something after the user interface is resized.
virtual bool OnHostRequestingAboutBox ()
virtual void OnHostIdentified ()
Implement this to do something specific when IPlug becomes aware of the particular host that is hosting the plug-in.
virtual bool GetMidiNoteText (int noteNumber, char *str) const
Override this method to provide custom text linked to MIDI note numbers in API classes that support that (VST2) Typically this might be used for a drum machine plug-in, in order to label a certainty "kick drum" etc.
int NParams () const
IParam * GetParam (int paramIdx)
Get a pointer to one of the plug-ins IParam objects WARNING: The IPlugBase::mParams is accessed by multiple threads, and this method has no thread safety mechanism.
const char * GetPluginName () const
int GetPluginVersion (bool decimal) const
Get the plug-in version number.
void GetPluginVersionStr (WDL_String &str) const
Gets the plug-in version as a string.
const char * GetMfrName () const
Get the manufacturer name as a CString.
const char * GetProductName () const
Get the product name as a CString.
int GetUniqueID () const
int GetMfrID () const
virtual EHost GetHost ()
int GetHostVersion (bool decimal)
Get the host version number as an integer.
void GetHostVersionStr (WDL_String &str)
Get the host version number as a string.
EAPI GetAPI () const
const char * GetAPIStr () const
const char * GetArchStr () const
void GetBuildInfoStr (WDL_String &str) const
Used to get the build date of the plug-in and architecture/api details in one string.
bool DoesStateChunks () const
bool HasUI () const
int Width () const
int Height () const
void DirtyParameters ()
This method will loop through all parameters, telling the host that they changed.
virtual void ResizeGraphics ()=0
Call this method in order to notify the API of a graphics resize.
virtual void BeginInformHostOfParamChange (int paramIdx)=0
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
virtual void EndInformHostOfParamChange (int paramIdx)=0
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
void SetParameterValue (int paramIdx, double normalizedValue)
SetParameterValue is called from the UI in the middle of a parameter change gesture (possibly via delegate) in order to update a parameter's value.
virtual void InformHostOfProgramChange ()
Implemented by the API class, called by the UI (etc) when the plug-in initiates a program/preset change (not applicable to all APIs)
int NParamGroups ()
int AddParamGroup (const char *name)
Called to add a parameter group name, when a unique group name is discovered.
const char * GetParamGroupName (int idx)
Get the parameter group name as a particular index.
void InitChunkWithIPlugVer (IByteChunk &chunk)
int GetIPlugVerFromChunk (const IByteChunk &chunk, int &pos)
Helper method to retrieve the IPlug version number from the beginning of the byte chunk.
void SetHost (const char *host, int version)
Called to set the name of the current host, if known.
virtual void HostSpecificInit ()
This method is called by some API classes, in order to do specific initialisation for particular problematic hosts.
bool SerializeParams (IByteChunk &chunk)
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
int UnserializeParams (const IByteChunk &chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
void OnParamReset (EParamSource source)
Calls OnParamChange() for each parameter and finally OnReset().
Public Member Functions inherited from IDelegate
virtual void ResizeGraphicsFromUI ()
Additional Inherited Members
Public Attributes inherited from IPlugBase
WDL_Mutex mParams_mutex
Lock when accessing mParams (including via GetParam) from the audio thread.
WDL_String mParamDisplayStr
Protected Attributes inherited from IPlugBase
WDL_String mPluginName
The name of this plug-in.
WDL_String mProductName
Product name: if the plug-in is part of collection of plug-ins it might be one product.
WDL_String mMfrName
Plug-in Manufacturer name.
int mUniqueID
int mMfrID
int mVersion
Plug-in version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
int mHostVersion = 0
Host version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
EHost mHost = kHostUninit
Host that has been identified, see EHost enum.
EAPI mAPI
API of this instance.
bool mStateChunks = false
true if the plug-in does opaque state chunks.
bool mHasUI = false
true if the plug-in has a user interface.
int mWidth = 0
The default width of the plug-in UI if it has an interface.
int mHeight = 0
The default height of the plug-in UI if it has an interface.
WDL_PtrList< const char > mParamGroups
A list of unique cstrings found specified as "parameter groups" when defining IParams.
WDL_PtrList< IParam > mParams
A list of IParam objects.
Detailed Description
An IPlugBase class for an IPlug plug-in that uses IGraphics for it's UI.
Definition at line 14 of file IPlugBaseGraphics.h.
Member Function Documentation
void IPlugBaseGraphics::BeginInformHostOfParamChangeFromUI (int paramIdx) inline override virtual
Called by the user interface at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
Parameters
paramIdx The index of the parameter that is changing value
Implements IDelegate.
Definition at line 37 of file IPlugBaseGraphics.h.
References IPlugBase::BeginInformHostOfParamChange().
void IPlugBaseGraphics::EndInformHostOfParamChangeFromUI (int paramIdx) inline override virtual
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
Parameters
paramIdx The index of the parameter that is changing value
Implements IDelegate.
Definition at line 38 of file IPlugBaseGraphics.h.
References IPlugBase::EndInformHostOfParamChange().
void* IPlugBaseGraphics::GetAAXViewInterface () inline override virtual
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
Returns
pointer to the class that implements the IAAXViewInterface
Reimplemented from IPlugBase.
Definition at line 22 of file IPlugBaseGraphics.h.
const IParam* IPlugBaseGraphics::GetParamObjectFromUI (int paramIdx) inline override virtual
Called by the user interface in order to get a const pointer to an IParam object.
Parameters
paramIdx The index of the parameter to be retrieved
Returns
Pointer to an IParam object
Implements IDelegate.
Definition at line 35 of file IPlugBaseGraphics.h.
References IPlugBase::GetParam().
void IPlugBaseGraphics::OnRestoreState () override virtual
If you override this method you should call this parent, or implement the same functionality in order to get controls to update, when state is restored.
Reimplemented from IPlugBase.
Definition at line 33 of file IPlugBaseGraphics.cpp.
References IPlugBase::mParams, and SendParameterValueToUIFromDelegate().
void * IPlugBaseGraphics::OpenWindow (void * pHandle) override virtual
Override this method when not using IGraphics in order to return a platform view handle e.g.
NSView, UIView, HWND
Reimplemented from IPlugBase.
Definition at line 46 of file IPlugBaseGraphics.cpp.
References IGraphics::OpenWindow().
void IPlugBaseGraphics::PrintDebugInfo () const override virtual
Helper method, used to print some info to the console in debug builds.
Can be overridden in other IPlugBases, for specific functionality, such as printing UI details.
Reimplemented from IPlugBase.
Definition at line 65 of file IPlugBaseGraphics.cpp.
References IGraphics::FPS(), IPlugBase::GetBuildInfoStr(), IGraphics::GetDrawingAPIStr(), IPlugBase::PrintDebugInfo(), and IGraphics::UserHomePath().
void IPlugBaseGraphics::SendParameterValueToUIFromAPI (int paramIdx, double value, bool normalized) override virtual
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange()
Parameters
paramIdx The index of the parameter that changed
value The new value
normalized /true if
value is normalised
Reimplemented from IPlugBase.
Definition at line 60 of file IPlugBaseGraphics.cpp.
References SendParameterValueToUIFromDelegate().
void IPlugBaseGraphics::SendParameterValueToUIFromDelegate (int paramIdx, double value, bool normalized) override virtual
This method is called by the API class in order to update the user interface with the new parameter values, typically after automation.
In IGraphics plug-ins, this will update any IControls that have their mParamIdx set > -1
Parameters
paramIdx The index of the parameter to be updated
value The new value of the parameter
normalized true if value is normalised
Implements IDelegate.
Definition at line 89 of file IPlugBaseGraphics.cpp.
References IGraphics::GetControl(), IPlugBase::GetParam(), IGraphics::NControls(), IControl::ParamIdx(), and IControl::SetValueFromDelegate().
Referenced by OnRestoreState(), and SendParameterValueToUIFromAPI().
void IPlugBaseGraphics::SetControlValueFromDelegate (int controlIdx, double normalizedValue) override virtual
In IGraphics plug-ins, this method is used to update IControls in the user interface from the plug-in class, when the control is not linked to a parameter, for example a typical use case would be a meter control.
It is called by the IPlug "user" a.k.a you - not by an API class. Somewhere in ProcessBlock() the plug-in would call this method to update the IControl's value. If you are not using IGraphics, you could use it in a similar way, as long as your control/meter has a unique index
Parameters
controlIdx The index of the control in the IGraphics::mControls list.
normalizedValue The normalised value to set the control to. This will modify IControl::mValue;
Implements IDelegate.
Definition at line 81 of file IPlugBaseGraphics.cpp.
References IGraphics::GetControl(), and IControl::SetValueFromDelegate().
void IPlugBaseGraphics::SetParameterValueFromUI (int paramIdx, double normalizedValue) inline override virtual
Called by the user interface during a parameter change gesture, in order to notify the host of the new value (via a call in the API class)
Parameters
paramIdx The index of the parameter that is changing value
value The new normalised value of the parameter
Implements IDelegate.
Definition at line 36 of file IPlugBaseGraphics.h.
References IPlugBase::SetParameterValue().
The documentation for this class was generated from the following files:
IPlugBaseGraphics.h
IPlugBaseGraphics.cpp