WDL-OL/IPlug: IPlugVST Class Reference
IPlugVST Class Reference
IPlug::APIClasses
VST2.4 API base class for an IPlug plug-in, inherits from IPlugBase or IPlugBaseGraphics.
#include <IPlugVST.h>
Public Member Functions
IPlugVST (IPlugInstanceInfo instanceInfo, IPlugConfig config)
void BeginInformHostOfParamChange (int idx) override
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
void InformHostOfParamChange (int idx, double normalizedValue) override
Implemented by the API class, called by the UI via SetParameterValue() with the value of a parameter change gesture.
void EndInformHostOfParamChange (int idx) override
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
void InformHostOfProgramChange () override
Implemented by the API class, called by the UI (etc) when the plug-in initiates a program/preset change (not applicable to all APIs)
EHost GetHost () override
void ResizeGraphics () override
Call this method in order to notify the API of a graphics resize.
void HostSpecificInit () override
This method is called by some API classes, in order to do specific initialisation for particular problematic hosts.
void SetLatency (int samples) override
Call this if the latency of your plug-in changes after initialization (perhaps from OnReset()) This may not be supported by the host.
bool SendMidiMsg (const IMidiMsg &msg) override
Send a single MIDI message.
bool SendSysEx (ISysEx &msg) override
Send a single MIDI System Exclusive (SysEx) message.
audioMasterCallback GetHostCallback ()
AEffect GetAEffect ()
Public Member Functions inherited from IPlugBaseGraphics
IPlugBaseGraphics (IPlugConfig config, EAPI plugAPI)
void * GetAAXViewInterface () override
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
void * OpenWindow (void *pHandle) override
Override this method when not using IGraphics in order to return a platform view handle e.g.
void CloseWindow () override
Override this method when not using IGraphics if you need to free resources etc when the window closes.
void SendParameterValueToUIFromAPI (int paramIdx, double value, bool normalized) override
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange()
void PrintDebugInfo () const override
Helper method, used to print some info to the console in debug builds.
virtual void OnRestoreState () override
If you override this method you should call this parent, or implement the same functionality in order to get controls to update, when state is restored.
void SetControlValueFromDelegate (int controlIdx, double normalizedValue) override
In IGraphics plug-ins, this method is used to update IControls in the user interface from the plug-in class, when the control is not linked to a parameter, for example a typical use case would be a meter control.
void SendParameterValueToUIFromDelegate (int paramIdx, double value, bool normalized) override
This method is called by the API class in order to update the user interface with the new parameter values, typically after automation.
const IParam * GetParamObjectFromUI (int paramIdx) override
Called by the user interface in order to get a const pointer to an IParam object.
void SetParameterValueFromUI (int paramIdx, double value) override
Called by the user interface during a parameter change gesture, in order to notify the host of the new value (via a call in the API class)
void BeginInformHostOfParamChangeFromUI (int paramIdx) override
Called by the user interface at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void EndInformHostOfParamChangeFromUI (int paramIdx) override
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void AttachGraphics (IGraphics *pGraphics)
IGraphics * GetUI ()
Public Member Functions inherited from IPlugBase
IPlugBase (IPlugConfig config, EAPI plugAPI)
virtual void OnParamChange (int paramIdx, EParamSource source)
Override this method to do something when a parameter changes.
virtual void OnParamChange (int paramIdx)
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
virtual bool SerializeState (IByteChunk &chunk)
Override this method to serialize custom state data, if your plugin does state chunks.
virtual int UnserializeState (const IByteChunk &chunk, int startPos)
Override this method to unserialize custom state data, if your plugin does state chunks.
virtual bool CompareState (const uint8_t *pIncomingState, int startPos)
Override this method to implement a custom comparison of incoming state data with your plug-ins state data, in order to support the ProTools compare light when using custom state chunks.
virtual void OnUIOpen ()
Override this method to be notified when the UI is opened.
virtual void OnUIClose ()
Override this method to be notified when the UI is closed.
virtual void OnWindowResize ()
Implement this to do something after the user interface is resized.
virtual bool OnHostRequestingAboutBox ()
virtual void OnHostIdentified ()
Implement this to do something specific when IPlug becomes aware of the particular host that is hosting the plug-in.
virtual bool GetMidiNoteText (int noteNumber, char *str) const
Override this method to provide custom text linked to MIDI note numbers in API classes that support that (VST2) Typically this might be used for a drum machine plug-in, in order to label a certainty "kick drum" etc.
int NParams () const
IParam * GetParam (int paramIdx)
Get a pointer to one of the plug-ins IParam objects WARNING: The IPlugBase::mParams is accessed by multiple threads, and this method has no thread safety mechanism.
const char * GetPluginName () const
int GetPluginVersion (bool decimal) const
Get the plug-in version number.
void GetPluginVersionStr (WDL_String &str) const
Gets the plug-in version as a string.
const char * GetMfrName () const
Get the manufacturer name as a CString.
const char * GetProductName () const
Get the product name as a CString.
int GetUniqueID () const
int GetMfrID () const
int GetHostVersion (bool decimal)
Get the host version number as an integer.
void GetHostVersionStr (WDL_String &str)
Get the host version number as a string.
EAPI GetAPI () const
const char * GetAPIStr () const
const char * GetArchStr () const
void GetBuildInfoStr (WDL_String &str) const
Used to get the build date of the plug-in and architecture/api details in one string.
bool DoesStateChunks () const
bool HasUI () const
int Width () const
int Height () const
void DirtyParameters ()
This method will loop through all parameters, telling the host that they changed.
void SetParameterValue (int paramIdx, double normalizedValue)
SetParameterValue is called from the UI in the middle of a parameter change gesture (possibly via delegate) in order to update a parameter's value.
int NParamGroups ()
int AddParamGroup (const char *name)
Called to add a parameter group name, when a unique group name is discovered.
const char * GetParamGroupName (int idx)
Get the parameter group name as a particular index.
void InitChunkWithIPlugVer (IByteChunk &chunk)
int GetIPlugVerFromChunk (const IByteChunk &chunk, int &pos)
Helper method to retrieve the IPlug version number from the beginning of the byte chunk.
void SetHost (const char *host, int version)
Called to set the name of the current host, if known.
bool SerializeParams (IByteChunk &chunk)
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
int UnserializeParams (const IByteChunk &chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
void OnParamReset (EParamSource source)
Calls OnParamChange() for each parameter and finally OnReset().
Public Member Functions inherited from IDelegate
virtual void ResizeGraphicsFromUI ()
Public Member Functions inherited from IPlugProcessor< PLUG_SAMPLE_DST >
IPlugProcessor (IPlugConfig config, EAPI plugAPI)
virtual void ProcessBlock (PLUG_SAMPLE_DST **inputs, PLUG_SAMPLE_DST **outputs, int nFrames)
Override in your plug-in class to process audio In ProcessBlock you are always guaranteed to get valid pointers to all the channels the plugin requested (the maximum possible input channel count and the maximum possible output channel count including multiple buses).
virtual void ProcessMidiMsg (const IMidiMsg &msg)
Override this method to handle incoming MIDI messages.
virtual void ProcessSysEx (ISysEx &msg)
Override this method to handle incoming MIDI System Exclusive (SysEx) messages.
virtual void OnReset ()
Override this method in your plug-in class to do something prior to playback etc.
virtual void OnActivate (bool active)
Override OnActivate() which should be called by the API class when a plug-in is "switched on" by the host on a track when the channel count is known.
virtual void OnIdle ()
Override this method to get an "idle"" call from the audio processing thread in VST2 plug-ins.
bool SendMidiMsgs (WDL_TypedBuf< IMidiMsg > &msgs)
Send a collection of MIDI messages.
double GetSampleRate () const
int GetBlockSize () const
int GetLatency () const
int GetTailSize ()
bool GetBypassed () const
bool GetRenderingOffline () const
int GetSamplePos () const
double GetTempo () const
double GetSamplesPerBeat () const
void GetTimeSig (int &numerator, int &denominator)
int NIOConfigs () const
IOConfig * GetIOConfig (int idx)
int MaxNBuses (ERoute direction) const
Used to determine the maximum number of input or output buses based on what was specified in the channel I/O config string.
int MaxNChannelsForBus (ERoute direction, int busIdx) const
For a given input or output bus what is the maximum possible number of channels.
bool HasWildcardBus (ERoute direction) const
Check if we have any wildcard characters in the channel io configs.
int MaxNChannels (ERoute direction) const
bool IsChannelConnected (ERoute direction, int chIdx) const
int NChannelsConnected (ERoute direction) const
bool LegalIO (int NInputChans, int NOutputChans) const
Check if a certain configuration of input channels and output channels is allowed based on the channel I/O configs.
bool HasSidechainInput () const
int NSidechainChannels () const
void LimitToStereoIO ()
This is called by IPlugVST in order to limit a plug-in to stereo I/O for certain picky hosts /todo may no longer be relevant.
bool IsInstrument () const
bool DoesMIDI () const
void SetChannelLabel (ERoute direction, int idx, const char *formatStr, bool zeroBased=false)
This allows you to label input/output channels in supporting VST2 hosts.
void SetTailSize (int tailSize)
Call this method if you need to update the tail size at runtime, for example if the decay time of your reverb effect changes Some apis have special interpretations of certain numbers.
void _SetSampleRate (double sampleRate)
void _SetBlockSize (int blockSize)
void _SetBypassed (bool bypassed)
void _SetTimeInfo (const ITimeInfo &timeInfo)
void _SetRenderingOffline (bool renderingOffline)
const WDL_String & _GetChannelLabel (ERoute direction, int idx)
Public Member Functions inherited from IPlugPresetHandler
IPlugPresetHandler (IPlugConfig config, EAPI plugAPI)
void AttachPresetHandler (void *pPlug)
Called by API class in order to attach this.
virtual void PresetsChangedByHost ()
void EnsureDefaultPreset ()
void MakeDefaultPreset (const char *name=0, int nPresets=1)
void MakePreset (const char *name,...)
void MakePresetFromNamedParams (const char *name, int nParamsNamed,...)
void MakePresetFromChunk (const char *name, IByteChunk &chunk)
void MakePresetFromBlob (const char *name, const char *blob, int sizeOfChunk)
void PruneUninitializedPresets ()
bool SerializePresets (IByteChunk &chunk)
int UnserializePresets (IByteChunk &chunk, int startPos)
void ModifyCurrentPreset (const char *name=0)
int NPresets ()
int GetCurrentPresetIdx ()
bool RestorePreset (int idx)
bool RestorePreset (const char *name)
const char * GetPresetName (int idx)
void DumpPresetSrcCode (const char *file, const char *paramEnumNames[])
void DumpPresetBlob (const char *file)
void DumpBankBlob (const char *file)
bool SaveProgramAsFXP (const char *file)
bool SaveBankAsFXB (const char *file)
bool LoadProgramFromFXP (const char *file)
bool LoadBankFromFXB (const char *file)
Public Attributes
AEffect mAEffect
Public Attributes inherited from IPlugBase
WDL_Mutex mParams_mutex
Lock when accessing mParams (including via GetParam) from the audio thread.
WDL_String mParamDisplayStr
Public Attributes inherited from IPlugPresetHandler
int mCurrentPresetIdx = 0
void * mPlugBase = nullptr
WDL_PtrList< IPreset > mPresets
Additional Inherited Members
Static Public Member Functions inherited from IPlugProcessor< PLUG_SAMPLE_DST >
static int ParseChannelIOStr (const char *IOStr, WDL_PtrList< IOConfig > &channelIOList, int &totalNInChans, int &totalNOutChans, int &totalNInBuses, int &totalNOutBuses)
A static method to parse the config.h channel I/O string.
Protected Member Functions inherited from IPlugProcessor< PLUG_SAMPLE_DST >
void _SetChannelConnections (ERoute direction, int idx, int n, bool connected)
void _AttachBuffers (ERoute direction, int idx, int n, PLUG_SAMPLE_DST **ppData, int nFrames)
void _AttachBuffers (ERoute direction, int idx, int n, PLUG_SAMPLE_SRC **ppData, int nFrames)
void _PassThroughBuffers (PLUG_SAMPLE_SRC type, int nFrames)
void _PassThroughBuffers (PLUG_SAMPLE_DST type, int nFrames)
void _ProcessBuffers (PLUG_SAMPLE_SRC type, int nFrames)
void _ProcessBuffers (PLUG_SAMPLE_DST type, int nFrames)
void _ProcessBuffersAccumulating (int nFrames)
void _ZeroScratchBuffers ()
Protected Attributes inherited from IPlugBase
WDL_String mPluginName
The name of this plug-in.
WDL_String mProductName
Product name: if the plug-in is part of collection of plug-ins it might be one product.
WDL_String mMfrName
Plug-in Manufacturer name.
int mUniqueID
int mMfrID
int mVersion
Plug-in version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
int mHostVersion = 0
Host version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
EHost mHost = kHostUninit
Host that has been identified, see EHost enum.
EAPI mAPI
API of this instance.
bool mStateChunks = false
true if the plug-in does opaque state chunks.
bool mHasUI = false
true if the plug-in has a user interface.
int mWidth = 0
The default width of the plug-in UI if it has an interface.
int mHeight = 0
The default height of the plug-in UI if it has an interface.
WDL_PtrList< const char > mParamGroups
A list of unique cstrings found specified as "parameter groups" when defining IParams.
WDL_PtrList< IParam > mParams
A list of IParam objects.
Protected Attributes inherited from IPlugProcessor< PLUG_SAMPLE_DST >
NChanDelayLine< PLUG_SAMPLE_DST > * mLatencyDelay
Pointer to a multichannel delay line used to delay the bypassed signal when a plug-in with latency is bypassed.
Detailed Description
VST2.4 API base class for an IPlug plug-in, inherits from IPlugBase or IPlugBaseGraphics.
Definition at line 23 of file IPlugVST.h.
Member Function Documentation
void IPlugVST::BeginInformHostOfParamChange (int paramIdx) override virtual
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Implements IPlugBase.
Definition at line 74 of file IPlugVST.cpp.
void IPlugVST::EndInformHostOfParamChange (int paramIdx) override virtual
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Implements IPlugBase.
Definition at line 84 of file IPlugVST.cpp.
EHost IPlugVST::GetHost () override virtual
Returns
The host if it has been identified, see EHost enum for a list of possible hosts, implemented in the API class for VST2 and AUv2
Reimplemented from IPlugBase.
Definition at line 94 of file IPlugVST.cpp.
References IPlugBase::GetHost(), and IPlugBase::SetHost().
Referenced by HostSpecificInit().
void IPlugVST::HostSpecificInit () override virtual
This method is called by some API classes, in order to do specific initialisation for particular problematic hosts.
This is not the same as OnHostIdentified(), which you may implement in your plug-in class to do your own specific initialisation after a host has been identified
Reimplemented from IPlugBase.
Definition at line 180 of file IPlugVST.cpp.
References GetHost(), IPlugProcessor< PLUG_SAMPLE_DST >::LimitToStereoIO(), IPlugProcessor< PLUG_SAMPLE_DST >::MaxNChannels(), and IPlugBase::OnHostIdentified().
void IPlugVST::InformHostOfParamChange (int paramIdx, double normalizedValue) override virtual
Implemented by the API class, called by the UI via SetParameterValue() with the value of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
normalizedValue The new normalised value of the parameter being changed
Implements IPlugBase.
Definition at line 79 of file IPlugVST.cpp.
void IPlugVST::ResizeGraphics () override virtual
Call this method in order to notify the API of a graphics resize.
Implements IPlugBase.
Definition at line 121 of file IPlugVST.cpp.
References IPlugBase::HasUI(), IPlugBase::Height(), IPlugBase::OnWindowResize(), and IPlugBase::Width().
bool IPlugVST::SendMidiMsg (const IMidiMsg & msg) override virtual
Send a single MIDI message.
Parameters
msg The IMidiMsg to send
Returns
true if successful
Implements IPlugProcessor< PLUG_SAMPLE_DST >.
Definition at line 151 of file IPlugVST.cpp.
bool IPlugVST::SendSysEx (ISysEx & msg) override virtual
Send a single MIDI System Exclusive (SysEx) message.
Parameters
msg The ISysEx to send
Returns
true if successful
Reimplemented from IPlugProcessor< PLUG_SAMPLE_DST >.
Definition at line 166 of file IPlugVST.cpp.
void IPlugVST::SetLatency (int latency) override virtual
Call this if the latency of your plug-in changes after initialization (perhaps from OnReset()) This may not be supported by the host.
The method is virtual because it's overridden in API classes.
Parameters
samples Latency in samples
Reimplemented from IPlugProcessor< PLUG_SAMPLE_DST >.
Definition at line 133 of file IPlugVST.cpp.
References IPlugProcessor< sampleType >::SetLatency().
The documentation for this class was generated from the following files:
IPlugVST.h
IPlugVST.cpp